spring.application.name=equipment-management
spring.datasource.url=jdbc:postgresql://localhost:5432/equipment_management
spring.datasource.username=postgres
spring.datasource.password=Emad@2811

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true